using Microsoft.EntityFrameworkCore.Migrations;

namespace SEDC.Lamazon.DataAccess.Migrations
{
    public partial class InsertNewProducts_DemoPurposes : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
              table: "ProductCategories",
              keyColumn: "Id",
              keyValues: new object[] { 5, 6 },
              column: "Name",
              values: new object[] { "Software", "Computers" }
            );

            migrationBuilder.InsertData(
             table: "Products",
             columns: new[] { "Name", "Description", "ImageUrl", "ProductCategoryId", "Price", "ProductStatusId", "IsFeatured" },
             values: new object[,]
             {
                    //BOOKS
                    { "Pro ASP.NET Core 6: Develop Cloud-Ready Web Applications Using MVC, Blazor, and Razor Pages 9th ed. Edition", "Professional developers will produce leaner applications for the ASP.NET Core platform using the guidance in this best-selling book, now in its 9th edition and updated for ASP.NET Core for .NET 6. It contains detailed explanations of the ASP.NET Core platform and the application frameworks it supports. This cornerstone guide puts ASP.NET Core for .NET 6 into context and dives deep into the tools and techniques required to build modern, extensible web applications. New features and capabilities such as MVC, Razor Pages, Blazor Server, and Blazor WebAssembly are covered, along with demonstrations of how they are applied.\r\n\r\nASP.NET Core for .NET 6 is the latest evolution of Microsoft’s ASP.NET web platform and provides a \"host-agnostic\" framework and a high-productivity programming model that promotes cleaner code architecture, test-driven development, and powerful extensibility.\r\n\r\nAuthor Adam Freeman has thoroughly revised this market-leading book and explains how to get the most from ASP.NET Core for .NET 6. He starts with the nuts-and-bolts topics, teaching you about middleware components, built-in services, request model binding, and more. As you gain knowledge and confidence, he introduces increasingly more complex topics and advanced features, including endpoint routing and dependency injection. He goes in depth to give you the knowledge you need.\r\n\r\nThis book follows the same format and style as the popular previous editions but brings everything up to date for the new ASP.NET Core for .NET 6 release and broadens the focus to include all of the ASP.NET Core platform. You will appreciate the fully worked case study of a functioning ASP.NET Core application that you can use as a template for your own projects.\r\n\r\nSource code for this book can be found at https://github.com/Apress/pro-asp.net-core-6.", "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/41pNC0JrGnL._SX344_BO1,204,203,200_.jpg", 4, 44.99, 1, false },
                    { "Professional ASP.NET MVC 5", "Available at a lower price from other sellers that may not offer free Prime shipping.\r\nASP.NET MVC insiders cover the latest updates to the technology in this popular Wrox reference\r\n\r\nMVC 5 is the newest update to the popular Microsoft technology that enables you to build dynamic, data-driven websites. Like previous versions, this guide shows you step-by-step techniques on using MVC to best advantage, with plenty of practical tutorials to illustrate the concepts. It covers controllers, views, and models; forms and HTML helpers; data annotation and validation; membership, authorization, and security.\r\n\r\nMVC 5, the latest version of MVC, adds sophisticated features such as single page applications, mobile optimization, and adaptive rendering\r\nA team of top Microsoft MVP experts, along with visionaries in the field, provide practical advice on basic and advanced MVC topics\r\nCovers controllers, views, models, forms, data annotations, authorization and security, Ajax, routing, ASP.NET web API, dependency injection, unit testing, real-world application, and much more\r\nProfessional ASP.NET MVC 5 is the comprehensive resource you need to make the best use of the updated Model-View-Controller technology.", "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51iINBCaUnL._SX397_BO1,204,203,200_.jpg", 4, 36.28, 1, false },
                    { "Pro ASP.NET MVC 5 (Expert's Voice in ASP.Net)", "Available at a lower price from other sellers that may not offer free Prime shipping.\r\nThe ASP.NET MVC 5 Framework is the latest evolution of Microsoft’s ASP.NET web platform. It provides a high-productivity programming model that promotes cleaner code architecture, test-driven development, and powerful extensibility, combined with all the benefits of ASP.NET.\r\nASP.NET MVC 5 contains a number of advances over previous versions, including the ability to define routes using C# attributes and the ability to override filters. The user experience of building MVC applications has also been substantially improved. The new, more tightly integrated, Visual Studio 2013 IDE has been created specifically with MVC application development in mind and provides a full suite of tools to improve development times and assist in reporting, debugging and deploying your code.", "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/517TOKqsopL._SX404_BO1,204,203,200_.jpg", 4, 45.96, 1, false },
                    { ".NET Interview Questions for Freshers and Experienced: ASP.NET,C#,MSSQL,MVC,WEB API", "This is a .NET Interview questions book for Freshers and Experienced candidates. It Covers questions from Begineer to intermediate and then to expert level. Additional General questions are also added in this Edition. This book covers questions from ASP.NET,C#,MVC,MSSQL and WEB API.\r\nNote: The content in this book is referred from the websites mentioned in the bibliography of the book and such content is available in the public domain. The Authors work is understanding the topics and bringing the best questions and their right answers together as per his knowledge and Experience. He has selected the most frequently asked interview questions on .NET as per his own Experience.", "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/414qiW0QxfS._SX352_BO1,204,203,200_.jpg", 4, 11.0, 1, false },

                    //SOFTWARE
                    { "Synology IP Camera License Pack for 8 (CLP8)", "By default, two camera licenses are installed. By applying the license key on the Surveillance Station user interface, you will be able to set up and manage more cameras on the network.\r\nTo find out the maximum number of IP cams supported on each Disk Station, please refer to the specifications of each model.\r\nSynology Surveillance Station has different billing methods for particular cameras, such as panoramic, multi-lens cameras and video server for analog cameras.", "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/7172S+RaIdL._AC_SX679_.jpg", 5, 379.99, 1, false },
                    { "McAfee Total Protection 2022", "AWARD WINNING ANTIVIRUS: Rest easy knowing McAfee’s protecting you from the latest threats\r\nPROTECT YOUR IDENTITY:  We'll monitor your life online, from bank account numbers, credit cards, to your emails and more.\r\nBROWSE CONFIDENTLY AND PRIVATELY: Secure VPN keeps your info safe from prying eyes\r\nSEE HOW SAFE YOU ARE BEING ONLINE: Get your personalized protection score, identify weaknesses and get help to fix them.\r\nBANK, SHOP and CONNECT WORRY-FREE: be warned about risky websites before you click\r\nSECURE YOUR ACCOUNTS: Generate and store complex passwords with a password manager\r\nPHYSICAL KEY CARD DELIVERY: Product with dlownload code and activation instructions will be shipped to your address.", "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/71vl+6VhKaL._AC_SX569_.jpg", 5, 21.99, 1, false },

                    //COMPUTERS
                    { "Microsoft Surface Laptop 3", "A like-new experience. Backed by a one-year satisfaction guarantee.\r\nThis Renewed Premium computer is shipped and sold by Amazon and is guaranteed to work and look like new. It has been extensively screened, repaired, tested and sanitized to the manufacturer's standards, and contains an original charger and cord; all in brand-new, premium packaging. It comes with the same one-year warranty as a brand new product.", "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51MPpf-qawL._AC_SX466_.jpg", 6, 499.0, 1, false },
                    { "Microsoft Surface Duo 128GB", "Room to focus with two screens. Open and view two apps at once or span one across both screens.\r\nFlexibility to do more. Choose your mode for the task at hand and tackle to-dos with dual-screen enhanced apps.\r\nGet the best of Microsoft 365 mobile experiences and every android app in the google play store.\r\nOriginal design, created by surface. Thin, light, and versatile design does what you want it to, with revolutionary 360° hinge and dual pixelsense fusion displays.\r\nHold like a book, get more screen when you need it, take notes, make calls, or watch a favorite show.\r\nConnector type: USB Type C\r\nOperating system: Android 10.0\r\nWireless communication technology: Cellular", "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/711UVfyz+FL._AC_SX466_.jpg", 6, 339.82, 1, false },
             });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
